{ lib
, buildDotnetModule
, fetchFromGitHub
, ...
}:

buildDotnetModule rec {
  pname = "mi-engine";
  version = "1.17.0";

  src = fetchFromGitHub {
    owner = "microsoft";
    repo = "MIEngine";
    rev = "v${version}";
    hash = "sha256-ZDIOoLZ+VvZ7y6TaH+ynjofuZjeLNYv2qMC11NHUADk=";
  };


  projectFile = "src/MIDebugEngine-Unix.sln";

  # Generated by running <package>.passthru.fetch-deps
  # To make it work, leave the option as []
  nugetDeps = ./deps.nix;

  meta = with lib; {
    description = "The Visual Studio MI Debug Engine (\"MIEngine\") provides an open-source Visual Studio Debugger extension that works with MI-enabled debuggers such as gdb and lldb";
    homepage = "https://github.com/microsoft/MIEngine";
    license = licenses.mit;
    maintainers = with maintainers; [ ];
    mainProgram = "mi-engine";
    platforms = platforms.all;
  };
}
